// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyiypgymxtstzjtnuouc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aXlwZ3lteHRzdHpqdG51b3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwOTIwMDgsImV4cCI6MjA2MjY2ODAwOH0.hFl0JQHBZe5PWhtfuXz4g4hB9jyc7Slg21Zp_Bhfb50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);